import type { CaseSearchResult } from "../../../domain/models/case-note.model";
import type { Dispatch, FormEvent, SetStateAction } from "react";
import type { CaseCategory, CaseRecord } from "../../../domain/models/case.model";
import type { CaseDocumentRecord } from "../../../domain/models/case-document.model";
import type { CaseNoteRecord, CaseNoteType, ConfidentialLevel } from "../../../domain/models/case-note.model";
import type { ProtectedPersonRecord } from "../../../domain/models/protected-person.model";
import type { ContactRecord } from "../../../domain/models/contact.model";
import type { PreventionProcessRecord } from "../../../domain/models/prevention.model";
import type { BemProcessRecord } from "../../../domain/models/bem.model";
import type { EqualizationProcessRecord } from "../../../domain/models/equalization.model";
import type { TerminationHearingRecord } from "../../../domain/models/termination.model";
import type { ParticipationRecord } from "../../../domain/models/participation.model";
import type { WorkplaceAccommodationRecord } from "../../../domain/models/workplace-accommodation.model";
import type { CaseLegalReferenceRecord } from "../../../domain/models/knowledge.model";
import type { CasesViewProps, CaseToast } from "./casesViewTypes";
import type { CaseExplorerSelection, CaseProcessType } from "./caseWorkbenchTypes";
import type { CaseProcessDraft } from "./casesViewProcessUtils";
import type { ProcessTemplateModalState } from "./ProcessTemplateDocumentsModal";
import type { useCaseWorkbenchSearch } from "./useCaseWorkbenchSearch";
import type { useInlineCommands } from "./inlineCommands/useInlineCommands";
import type { useCaseProcessUpdates } from "./useCaseProcessUpdates";
import type { useProcessTemplateActions } from "./useProcessTemplateActions";
import type { useCaseProcessCreation } from "./useCaseProcessCreation";
import type { useCaseCrudActions } from "./useCaseCrudActions";
import type { useCaseNoteEditor } from "./useCaseNoteEditor";
import type { CaseDocumentActions } from "./useCaseDocuments";
export type SearchState = ReturnType<typeof useCaseWorkbenchSearch>;
export type ProcessUpdateActions = ReturnType<typeof useCaseProcessUpdates>;
export type TemplateActions = ReturnType<typeof useProcessTemplateActions>;
export type ProcessCreationActions = ReturnType<typeof useCaseProcessCreation>;
export type CrudActions = ReturnType<typeof useCaseCrudActions>;
export type NoteEditorActions = ReturnType<typeof useCaseNoteEditor>;

export type CasesViewRenderProps = {
  caseToast: CaseToast | null;
  visibleCases: CaseRecord[];
  selectedCaseId: string;
  filteredCases: CaseRecord[];
  caseFilter: string;
  setCaseFilter: Dispatch<SetStateAction<string>>;
  normalizedCaseRegisterPage: number;
  caseRegisterPageCount: number;
  caseRegisterPageSize: number;
  setCaseRegisterPage: Dispatch<SetStateAction<number>>;
  openCaseCreateModal: CrudActions["openCaseCreateModal"];
  selectedCase?: CaseRecord;
  selectedNote?: CaseNoteRecord;
  selectedDocument?: CaseDocumentRecord;
  selectedSearchResult?: CaseSearchResult;
  selectedPreventionProcess?: PreventionProcessRecord;
  selectedBemProcess?: BemProcessRecord;
  selectedTerminationProcess?: TerminationHearingRecord;
  selectedEqualizationProcess?: EqualizationProcessRecord;
  selectedEqualizationNotes: CaseNoteRecord[];
  selectedParticipationProcess?: ParticipationRecord;
  selectedWorkplaceAccommodationProcess?: WorkplaceAccommodationRecord;
  notes: CaseNoteRecord[];
  documents: CaseDocumentRecord[];
  caseLegalReferences: CaseLegalReferenceRecord[];
  casePreventionProcesses: PreventionProcessRecord[];
  caseBemProcesses: BemProcessRecord[];
  caseEqualizationProcesses: EqualizationProcessRecord[];
  caseTerminationProcesses: TerminationHearingRecord[];
  caseParticipationProcesses: ParticipationRecord[];
  caseWorkplaceAccommodationProcesses: WorkplaceAccommodationRecord[];
  isCaseChildrenLoading: boolean;
  selection: CaseExplorerSelection;
  setSelection: (selection: CaseExplorerSelection) => void;
  setSelectedCaseId: Dispatch<SetStateAction<string>>;
  searchQuery: SearchState["searchQuery"];
  searchOnlySelectedCase: SearchState["searchOnlySelectedCase"];
  searchResults: SearchState["searchResults"];
  selectedSearchSourceTypes: SearchState["selectedSearchSourceTypes"];
  searchError: SearchState["searchError"];
  searchInfo: SearchState["searchInfo"];
  isSearching: SearchState["isSearching"];
  runSearch: SearchState["runSearch"];
  setSearchQuery: SearchState["setSearchQuery"];
  setSearchOnlySelectedCase: SearchState["setSearchOnlySelectedCase"];
  setSelectedSearchSourceTypes: SearchState["setSelectedSearchSourceTypes"];
  documentActions: CaseDocumentActions;
  inlineCommands: ReturnType<typeof useInlineCommands>;
  caseNumber: string;
  displayName: string;
  category: CaseCategory;
  summary: string;
  selectedProtectedPersonId: string;
  protectedPersons: ProtectedPersonRecord[];
  error: string;
  isCaseCreateModalOpen: boolean;
  setCaseNumber: Dispatch<SetStateAction<string>>;
  setDisplayName: Dispatch<SetStateAction<string>>;
  setCategory: Dispatch<SetStateAction<CaseCategory>>;
  setSummary: Dispatch<SetStateAction<string>>;
  setSelectedProtectedPersonId: Dispatch<SetStateAction<string>>;
  cancelCaseCreateModal: CrudActions["cancelCaseCreateModal"];
  addCase: (event: FormEvent<HTMLFormElement>) => Promise<void>;
  addAnonymousCase: CrudActions["addAnonymousCase"];
  isNoteModalOpen: boolean;
  editingNote: CaseNoteRecord | null;
  noteTitle: string;
  noteDate: string;
  noteType: CaseNoteType;
  participants: string;
  content: string;
  nextSteps: string;
  cases: CaseRecord[];
  linkedCaseIds: string[];
  confidentialLevel: ConfidentialLevel;
  containsHealthData: boolean;
  noteError: string;
  noteInfo: string;
  setNoteTitle: Dispatch<SetStateAction<string>>;
  setNoteDate: Dispatch<SetStateAction<string>>;
  setNoteType: Dispatch<SetStateAction<CaseNoteType>>;
  setParticipants: Dispatch<SetStateAction<string>>;
  setConfidentialLevel: Dispatch<SetStateAction<ConfidentialLevel>>;
  setContainsHealthData: Dispatch<SetStateAction<boolean>>;
  toggleLinkedCase: (caseId: string, checked: boolean) => void;
  cancelNoteModal: () => void;
  saveNote: (event: FormEvent<HTMLFormElement>) => Promise<void>;
  caseProcessDraft: CaseProcessDraft | null;
  setCaseProcessDraft: Dispatch<SetStateAction<CaseProcessDraft | null>>;
  createCaseProcessFromDraft: ProcessCreationActions["createCaseProcessFromDraft"];
  contacts: ContactRecord[];
  processTemplateModal: ProcessTemplateModalState | null;
  setProcessTemplateModal: Dispatch<SetStateAction<ProcessTemplateModalState | null>>;
  renderAndDownloadProcessTemplate: TemplateActions["renderAndDownloadProcessTemplate"];
  legacyBindingCase: CaseRecord | null;
  legacyBindingError: string;
  openLegacyBindingDialog: (caseRecord: CaseRecord) => void;
  closeLegacyBindingDialog: () => void;
  assignLegacyCase: (protectedPersonId: string, reason: string) => Promise<void>;
  closedLegacyBulkCount: number;
  bulkMarkClosedLegacyCases: () => Promise<void>;
  onOpenExportHandover: () => void;
  onOpenImportHandover: () => void;
  onContinueExpiredHandover: () => Promise<void>;
  onOpenParticipationViolationPrefill: CasesViewProps["onOpenParticipationViolationPrefill"];
  onOpenCasePrivacyAction: (record: CaseRecord) => void;
  onOpenProcessDelete: (target: { id: string; processType: CaseProcessType; label?: string }) => void;
} & ProcessUpdateActions & Pick<TemplateActions, "openProcessTemplateModal"> & Pick<ProcessCreationActions, "openCaseProcessDraft"> & Pick<CrudActions, "deleteNote"> & Pick<NoteEditorActions, "startEditNote" | "openNewNoteModal">;
