import { IPC_CHANNELS } from '../ipc/channels.js';
import type { IpcInvoker } from './invoke.js';
import type { ConfigureElectionSetupInput, CreateElectionInput, ElectionBoardMemberRecord, ElectionBoardSessionRecord, ElectionCandidateRecord, ElectionObjectionRecord, ElectionPreparationOverview, ElectionProposalRecord, ElectionRecord, ElectionSetupAssessment, ElectionVoterFileImportInput, ElectionVoterFileImportResult, ElectionVoterImportFileSelection, ElectionVoterRecord, ElectionVoterSyncResult, GenerateElectionPreparationDocumentInput, SaveElectionBoardMemberInput, SaveElectionBoardSessionInput, SaveElectionCandidateInput, SaveElectionObjectionInput, SaveElectionProposalInput, SaveElectionVoterInput } from '../../src/app/core/models/election-workflow.model.js';
import type { ActivityJournalPrefill } from '../../src/app/core/models/activity-journal.model.js';
import type { SbvOfficeDocumentRecord } from '../../services/sbvOfficeWorkflowDocumentAdapter.js';
import type { ElectionCloseInput, ElectionDayChecklistInput, ElectionDocumentExportResult, ElectionExecutionOverview, ElectionMailBallotRecord, ElectionPhysicalRecord, ElectionResultRecord, ElectionTransferFileExportResult, ElectionTransferFileSelection, ElectionTransferInspection, GenerateElectionExecutionDocumentInput, RecordElectionAcceptanceInput, RecordElectionLotInput, RecordElectionTotalsInput, SaveElectionMailBallotInput, SaveElectionPhysicalRecordInput } from '../../src/app/core/models/election-execution.model.js';
import type { ElectionTransferEnvelope } from '../../services/electionTransferCryptoAdapter.js';
import type { ElectionTransferImportResult } from '../../services/electionTransferImportService.js';
export function createElectionsApi(invokeIpc:IpcInvoker){return{elections:{
 list:():Promise<ElectionRecord[]>=>invokeIpc(IPC_CHANNELS.electionsList),get:(id:string):Promise<ElectionRecord>=>invokeIpc(IPC_CHANNELS.electionsGet,id),create:(input:CreateElectionInput):Promise<ElectionRecord>=>invokeIpc(IPC_CHANNELS.electionsCreate,input),configureSetup:(id:string,input:ConfigureElectionSetupInput):Promise<ElectionSetupAssessment>=>invokeIpc(IPC_CHANNELS.electionsConfigureSetup,id,input),overview:(id:string):Promise<ElectionPreparationOverview>=>invokeIpc(IPC_CHANNELS.electionsOverview,id),saveVoter:(id:string,input:SaveElectionVoterInput):Promise<ElectionVoterRecord>=>invokeIpc(IPC_CHANNELS.electionsVoterSave,id,input),syncVotersFromPersons:(id:string):Promise<ElectionVoterSyncResult>=>invokeIpc(IPC_CHANNELS.electionsVotersSyncPersons,id),selectVoterImportFile:():Promise<ElectionVoterImportFileSelection>=>invokeIpc(IPC_CHANNELS.electionsVotersSelectImportFile),previewVoterImport:(input:ElectionVoterFileImportInput):Promise<import('../../src/app/core/models/protected-person.model.js').PersonImportPreviewResult>=>invokeIpc(IPC_CHANNELS.electionsVotersPreviewImport,input),importVotersFromPersonFile:(id:string,input:ElectionVoterFileImportInput):Promise<ElectionVoterFileImportResult>=>invokeIpc(IPC_CHANNELS.electionsVotersImportFile,id,input),saveBoardMember:(id:string,input:SaveElectionBoardMemberInput):Promise<ElectionBoardMemberRecord>=>invokeIpc(IPC_CHANNELS.electionsBoardMemberSave,id,input),saveBoardSession:(id:string,input:SaveElectionBoardSessionInput):Promise<ElectionBoardSessionRecord>=>invokeIpc(IPC_CHANNELS.electionsBoardSessionSave,id,input),saveObjection:(id:string,input:SaveElectionObjectionInput):Promise<ElectionObjectionRecord>=>invokeIpc(IPC_CHANNELS.electionsObjectionSave,id,input),saveCandidate:(id:string,input:SaveElectionCandidateInput):Promise<ElectionCandidateRecord>=>invokeIpc(IPC_CHANNELS.electionsCandidateSave,id,input),saveProposal:(id:string,input:SaveElectionProposalInput):Promise<ElectionProposalRecord>=>invokeIpc(IPC_CHANNELS.electionsProposalSave,id,input),startGracePeriod:(id:string,date:string):Promise<ElectionProposalRecord>=>invokeIpc(IPC_CHANNELS.electionsGracePeriodStart,id,date),recordNoticeIssued:(id:string,date:string):Promise<{recorded:boolean}>=>invokeIpc(IPC_CHANNELS.electionsNoticeIssued,id,date),markPreparation:(id:string):Promise<ElectionRecord>=>invokeIpc(IPC_CHANNELS.electionsMarkPreparation,id),journalPrefill:(id:string,activity:'preparation'|'board_work'|'voter_list'|'nominations'|'voting'|'counting'|'result'|'archive'):Promise<ActivityJournalPrefill>=>invokeIpc(IPC_CHANNELS.electionsJournalPrefill,id,activity),generateDocument:(id:string,input:GenerateElectionPreparationDocumentInput):Promise<SbvOfficeDocumentRecord>=>invokeIpc(IPC_CHANNELS.electionsGenerateDocument,id,input),
 executionOverview:(id:string):Promise<ElectionExecutionOverview>=>invokeIpc(IPC_CHANNELS.electionsExecutionOverview,id),
 recordElectionDayChecklist:(id:string,input:ElectionDayChecklistInput):Promise<ElectionExecutionOverview>=>invokeIpc(IPC_CHANNELS.electionsDayChecklistRecord,id,input),
 saveMailBallot:(id:string,input:SaveElectionMailBallotInput):Promise<ElectionMailBallotRecord>=>invokeIpc(IPC_CHANNELS.electionsMailBallotSave,id,input),
 recordTotals:(id:string,input:RecordElectionTotalsInput):Promise<ElectionExecutionOverview>=>invokeIpc(IPC_CHANNELS.electionsTotalsRecord,id,input),
 recordLotDecision:(id:string,input:RecordElectionLotInput):Promise<ElectionResultRecord>=>invokeIpc(IPC_CHANNELS.electionsLotRecord,id,input),
 recordAcceptance:(id:string,input:RecordElectionAcceptanceInput):Promise<ElectionExecutionOverview>=>invokeIpc(IPC_CHANNELS.electionsAcceptanceRecord,id,input),
 savePhysicalRecord:(id:string,input:SaveElectionPhysicalRecordInput):Promise<ElectionPhysicalRecord>=>invokeIpc(IPC_CHANNELS.electionsPhysicalRecordSave,id,input),
 close:(id:string,input:ElectionCloseInput):Promise<{closed:boolean}>=>invokeIpc(IPC_CHANNELS.electionsClose,id,input),
 generateExecutionDocument:(id:string,input:GenerateElectionExecutionDocumentInput):Promise<SbvOfficeDocumentRecord>=>invokeIpc(IPC_CHANNELS.electionsExecutionDocumentGenerate,id,input),
 exportPdfArchive:(id:string):Promise<SbvOfficeDocumentRecord>=>invokeIpc(IPC_CHANNELS.electionsArchivePdf,id),
 exportDocument:(documentId:string,suggestedFileName?:string):Promise<ElectionDocumentExportResult>=>invokeIpc(IPC_CHANNELS.electionsDocumentExport,documentId,suggestedFileName),
 exportTransfer:(id:string,passphrase:string):Promise<ElectionTransferEnvelope>=>invokeIpc(IPC_CHANNELS.electionsTransferExport,id,passphrase),
 inspectTransfer:(envelope:ElectionTransferEnvelope,passphrase:string):Promise<ElectionTransferInspection>=>invokeIpc(IPC_CHANNELS.electionsTransferInspect,envelope,passphrase),
 importTransfer:(envelope:ElectionTransferEnvelope,passphrase:string):Promise<ElectionTransferImportResult>=>invokeIpc(IPC_CHANNELS.electionsTransferImport,envelope,passphrase),
 exportTransferFile:(id:string,passphrase:string,suggestedFileName?:string):Promise<ElectionTransferFileExportResult>=>invokeIpc(IPC_CHANNELS.electionsTransferExportFile,id,passphrase,suggestedFileName),
 selectTransferFile:(passphrase:string):Promise<ElectionTransferFileSelection>=>invokeIpc(IPC_CHANNELS.electionsTransferSelectInspect,passphrase),
 importTransferFile:(fileToken:string,passphrase:string):Promise<ElectionTransferImportResult>=>invokeIpc(IPC_CHANNELS.electionsTransferImportFile,fileToken,passphrase),
}} as const;}
