import { AUDIT_PURPOSES } from './auditEventBuilders.js';

// Nur fest im Programm definierte Zwecktexte gelangen in das datensparsame Audit.
const STATIC_AUDIT_PURPOSES = [
  "Tresorpasswort geändert",
  "Tresorpasswort per Recovery-Key zurückgesetzt",
  "",
  "Aktuelles Ergebnis eines bewusst geladenen Verfahrens lesen",
  "Anregung/Beschwerde bearbeiten",
  "Arbeitgeberpflicht-Prüfvorgang anlegen",
  "Arbeitgeberpflicht-Prüfvorgang dokumentieren",
  "archive_pdf",
  "Aus einem lokalen SBV-Fall bewusst einen minimalen Gremia.BR-Sachverhalt anlegen",
  "Automatische Prüfung alter Klartext-Berichtsexporte abgeschlossen",
  "bem_process angelegt",
  "bem_process geändert",
  "Berechtigte Sachverhalte für die bewusste Verfahrensauswahl lesen",
  "Berechtigtes Gremium in Gremia.BR 2.0 lesen",
  "Beschlussdetails in Gremia.BR 2.0 lesen",
  "Beschlüsse einer Sitzung in Gremia.BR 2.0 lesen",
  "Bulk-Aktion abgeschlossene Altakten vormerken",
  "Datenschutzprüfung abgeschlossen",
  "Datenschutzprüfung angelegt",
  "Details eines ausdrücklich gewählten zugänglichen Verfahrens lesen",
  "Dokumente eines ausdrücklich gewählten Sicherheitsbereichs in Gremia.BR 2.0 lesen",
  "Dokumente in einem ausdrücklich gewählten Sicherheitsbereich in Gremia.BR 2.0 suchen",
  "Dokumentmetadaten in Gremia.BR 2.0 lesen",
  "Dokumentversion nach expliziter Nutzeraktion aus Gremia.BR 2.0 laden",
  "Dokumentversionen in Gremia.BR 2.0 lesen",
  "Eigene Aufgabe im ausdrücklich verknüpften Verfahren anlegen",
  "Eigene Aufgabendetails nach ausdrücklicher Auswahl lesen",
  "Eigene berechtigte Gremien in Gremia.BR 2.0 lesen",
  "Eigene offene Aufgaben nach bewusstem Gesamtabruf lesen",
  "Eigenen Zugriff auf ein bewusst ausgewähltes Dokument beantragen",
  "Ein bewusst gewähltes SBV-Verfahren zum neuen Sachverhalt anlegen",
  "Empfängerprofil aktiviert",
  "Empfängerprofil aktualisiert",
  "Empfängerprofil angelegt",
  "Empfängerprofil deaktiviert",
  "Empfängerprofil gelöscht",
  "equalization_process angelegt",
  "equalization_process geändert",
  "Erzeugtes PDF-Dokument verschlüsselt abgelegt; Audit enthält keine Dokumentinhalte.",
  "Externe Gremia.BR-Referenz aktualisiert",
  "Externe Gremia.BR-Referenz aus Fallakte entfernt",
  "Externe Gremia.BR-Referenz mit Fallakte verknüpft",
  "Fallakte angelegt",
  "Fallakte anonymisiert",
  "Fallakte endgültig gelöscht",
  "Fallakte mit Person verknüpft",
  "Fallakte strukturiert anonymisiert",
  "Fallaktenliste anzeigen",
  "Falldokument exportiert",
  "Falldokument gelöscht",
  "Falldokument importiert",
  "Falldokument zur Vorschau entschlüsselt",
  "Falldokumente anzeigen",
  "Fallmaßnahme geändert",
  "Fallmaßnahme gelöscht",
  "Fallnotiz angelegt",
  "Fallnotiz geändert",
  "Fallnotiz gelöscht",
  "Fallnotizen anzeigen",
  "Fehlende Informationen zu einem Gremia.BR-Verfahren anfordern",
  "Fortspeicherung begründet",
  "Freigaben eines bewusst ausgewählten Dokuments lesen",
  "Fristen eines bewusst geladenen Verfahrens lesen",
  "Geschützten Remote-Zugang nach ausdrücklicher Nutzeraktion lesen",
  "Gremia.BR-2.0-Session für explizite Nutzeraktion öffnen",
  "Gremia.BR-2.0-Sessionstatus prüfen",
  "Informationsanforderung nach ausdrücklicher Bestätigung abschließen",
  "Informationsanforderungen eines bewusst gewählten verknüpften Verfahrens lesen",
  "Inklusionsvereinbarung dokumentieren",
  "Interner Fallnotiz-Bezug angelegt",
  "Kontakt angelegt",
  "Kontakt geändert",
  "Kontakt gelöscht und Referenzen anonymisiert",
  "Kontakt über Fallnotiz-Inline-Befehl angelegt",
  "Kontaktliste anzeigen",
  "Legacy-Fallakte manuell zugeordnet",
  "Maßnahmen-Lifecycle",
  "Mobile-Begleit-App-Rückgabe importiert",
  "Mobile-Begleit-App-Snapshot erstellt",
  "Mobile-Begleitgerät aktiviert",
  "Mobile-Begleitgerät aktualisiert",
  "Mobile-Begleitgerät deaktiviert",
  "Mobile-Begleitgerät gekoppelt",
  "Mögliche Statusänderungen einer eigenen Aufgabe bewusst abrufen",
  "PDF-Report als verschlüsselter .gsbvpdf-Container erzeugt",
  "Personenverzeichnis: Person gelöscht",
  "prevention_process angelegt",
  "prevention_process geändert",
  "Protokoll einer Sitzung in Gremia.BR 2.0 lesen",
  "Rechtsnorm mit Fallakte über Fallnotiz-Inline-Befehl verknüpft",
  "Rechtsnorm mit Fallakte verknüpft",
  "Rechtsnorm-Verknüpfung aus Fallakte entfernt",
  "Rückübergabe / Delta aus Urlaubsvertretung",
  "SBV-Beteiligungsverstoß-Dokument erzeugen",
  "SBV-Beteiligungsverstoß-Protokollierung",
  "SBV-Sitzung aktualisieren",
  "SBV-Sitzung anlegen",
  "SBV-Tagesordnung dokumentieren",
  "SBV-Thema als bewusste Agenda-Anforderung an eine Gremia.BR-Sitzung übergeben",
  "SBV-Verfahrensarten nach ausdrücklicher Auswahl laden",
  "SBV-Wahldurchführung dokumentiert",
  "SBV-Wahlvorbereitung dokumentiert",
  "Schutzklasse eines selbst übertragenen Dokuments bewusst ändern",
  "Schwerbehindertenversammlung aktualisieren",
  "Schwerbehindertenversammlung anlegen",
  "Signaturstatus der bewusst geöffneten Dokumentversion lesen",
  "Sitzungen eines berechtigten Gremiums in Gremia.BR 2.0 lesen",
  "Sitzungsdetails in Gremia.BR 2.0 lesen",
  "Status eigener Zugriffsanträge nach bewusstem Gesamtabruf lesen",
  "Status einer eigenen Aufgabe nach ausdrücklicher Bestätigung ändern",
  "Status Inklusionsbeauftragter dokumentieren",
  "Stellenbesetzung aktualisiert; Audit enthält keine Freitexte aus Verfahrensnotizen.",
  "Stellenbesetzung angelegt; Audit enthält keine Bewerberdaten oder Gesprächsinhalte.",
  "Stellenbesetzung gelöscht; zugehörige Interview-Ereignisse wurden kaskadiert gelöscht.",
  "system_check",
  "Tagesordnung in Gremia.BR 2.0 lesen",
  "Tagesordnungsversionen in Gremia.BR 2.0 lesen",
  "Temporäre Klartext-Arbeitskopien bereinigt",
  "termination_hearing angelegt",
  "termination_hearing geändert",
  "Themenmatrix Inklusionsvereinbarung aktualisieren",
  "Tresor automatisch gesperrt",
  "Tresor gesperrt",
  "Tresor per Passwort entsperrt",
  "Tresor per Recovery-Key entsperrt",
  "Übertragenes PDF fachlich mit dem SBV-Gremium verknüpfen",
  "Volltextsuche in personenbezogenen Falldaten",
  "Von der SBV ausgelöste Freigabe widerrufen",
  "Von der SBV bewusst ausgelöste Dokumentfreigabe an BR oder anderes Gremium",
  "Von Gremia.SBV erzeugtes PDF in den ausgewählten SBV-Arbeitsbereich übertragen",
  "Wiedervorlagen eines bewusst geladenen Verfahrens lesen",
] as const;

const allowedPurposes = new Set<string>([...STATIC_AUDIT_PURPOSES, ...Object.values(AUDIT_PURPOSES)]);

export function isAllowedAuditPurpose(value: string): boolean {
  return allowedPurposes.has(value);
}
