import { randomUUID } from 'node:crypto';
import type { DatabaseAdapter } from './databaseService.js';
import type { ElectionKind, ElectionProcedure, ElectionStatus, EligibilityBasis, OfficeType, ProposalStatus } from '../src/domain/models/election.model.js';
import type { ElectionBoardMemberRecord, ElectionBoardSessionRecord, ElectionCandidateRecord, ElectionObjectionRecord, ElectionProposalRecord, ElectionRecord, ElectionVoterRecord, SaveElectionBoardMemberInput, SaveElectionBoardSessionInput, SaveElectionCandidateInput, SaveElectionObjectionInput, SaveElectionProposalInput, SaveElectionVoterInput } from '../src/domain/models/election-workflow.model.js';

type ElectionRow={id:string;kind:ElectionKind;trigger_reason:string|null;procedure:ElectionProcedure|null;procedure_confirmed_at:string|null;procedure_decision_note:string|null;legal_rule_version:string;status:ElectionStatus;election_date:string|null;incumbent_term_end:string|null;office_term_start:string|null;office_term_end:string|null;calculated_next_regular_election_period:string|null;eligibility_check_date:string|null;eligible_disabled_employee_count:number;minimum_threshold_met:number;eligibility_check_basis:string|null;spatially_separated:number;eligible_count_snapshot:number;deputy_count:number;deputy_count_locked_at:string|null;created_at:string;updated_at:string};
type VoterRow={id:string;election_id:string;last_name:string;first_name:string;birth_date_optional:string|null;org_unit:string|null;eligibility_basis:EligibilityBasis;eligibility_verified_at:string|null;list_status:string;created_at:string;updated_at:string};
type MemberRow={id:string;election_id:string;role:string;name:string;employed_confirmed:number;adult_confirmed:number;appointed_at:string|null;created_at:string;updated_at:string};
type SessionRow={id:string;election_id:string;starts_at:string;participants_json:string;decisions_text:string|null;minutes_document_id:string|null;created_at:string;updated_at:string};
type CandidateRow={id:string;election_id:string;office_type:OfficeType;person_snapshot:string;birth_date:string|null;occupation:string|null;consent_at:string|null;eligibility_status:string;created_at:string;updated_at:string};
type ProposalRow={id:string;election_id:string;received_at:string;validity_status:ProposalStatus;correction_due_at:string|null;invalid_reason:string|null;created_at:string;updated_at:string};
type ObjectionRow={id:string;election_id:string;received_at:string;subject_ref:string;decision_at:string|null;decision:string|null;notified_at:string|null;created_at:string;updated_at:string};
const now=()=>new Date().toISOString();
const clean=(v:string|undefined)=>v?.trim()||null;
const mapElection=(r:ElectionRow):ElectionRecord=>({id:r.id,kind:r.kind,triggerReason:r.trigger_reason??undefined,procedure:r.procedure??undefined,procedureConfirmedAt:r.procedure_confirmed_at??undefined,procedureDecisionNote:r.procedure_decision_note??undefined,legalRuleVersion:r.legal_rule_version,status:r.status,electionDate:r.election_date??undefined,incumbentTermEnd:r.incumbent_term_end??undefined,officeTermStart:r.office_term_start??undefined,officeTermEnd:r.office_term_end??undefined,nextRegularElectionPeriod:r.calculated_next_regular_election_period??undefined,eligibilityCheckDate:r.eligibility_check_date??undefined,eligibleDisabledEmployeeCount:Number(r.eligible_disabled_employee_count),minimumThresholdMet:Boolean(r.minimum_threshold_met),eligibilityCheckBasis:r.eligibility_check_basis??undefined,spatiallySeparated:Boolean(r.spatially_separated),eligibleCountSnapshot:Number(r.eligible_count_snapshot),deputyCount:Number(r.deputy_count),deputyCountLockedAt:r.deputy_count_locked_at??undefined,createdAt:r.created_at,updatedAt:r.updated_at});
export class ElectionPreparationRepository{
 constructor(private readonly database:DatabaseAdapter){}
 listElections():ElectionRecord[]{return this.database.prepare<ElectionRow>('SELECT * FROM sbv_elections ORDER BY created_at DESC').all().map(mapElection);}
 getElection(id:string):ElectionRecord|undefined{const r=this.database.prepare<ElectionRow>('SELECT * FROM sbv_elections WHERE id=?').get(id);return r?mapElection(r):undefined;}
 insertElection(input:{id:string;kind:ElectionKind;triggerReason?:string;electionDate?:string;incumbentTermEnd?:string;officeTermStart?:string;officeTermEnd?:string;nextRegularElectionPeriod?:string;legalRuleVersion:string}):ElectionRecord{const t=now();this.database.prepare(`INSERT INTO sbv_elections(id,kind,trigger_reason,legal_rule_version,status,election_date,incumbent_term_end,office_term_start,office_term_end,calculated_next_regular_election_period,created_at,updated_at) VALUES(?,?,?,?,'draft',?,?,?,?,?,?,?)`).run(input.id,input.kind,clean(input.triggerReason),input.legalRuleVersion,clean(input.electionDate),clean(input.incumbentTermEnd),clean(input.officeTermStart),clean(input.officeTermEnd),clean(input.nextRegularElectionPeriod),t,t);return this.getElection(input.id)!;}
 updateSetup(id:string,input:{procedure:ElectionProcedure;procedureDecisionNote?:string;status:ElectionStatus;electionDate?:string;eligibilityCheckDate:string;eligibleCount:number;thresholdMet:boolean;basisJson:string;spatiallySeparated:boolean;deputyCount:number}):ElectionRecord{const t=now();this.database.prepare(`UPDATE sbv_elections SET procedure=?,procedure_confirmed_at=?,procedure_decision_note=?,status=?,election_date=COALESCE(?,election_date),eligibility_check_date=?,eligible_disabled_employee_count=?,minimum_threshold_met=?,eligibility_check_basis=?,spatially_separated=?,eligible_count_snapshot=?,deputy_count=?,updated_at=? WHERE id=?`).run(input.procedure,input.status==='procedure_confirmed'?t:null,clean(input.procedureDecisionNote),input.status,clean(input.electionDate),input.eligibilityCheckDate,input.eligibleCount,input.thresholdMet?1:0,input.basisJson,input.spatiallySeparated?1:0,input.eligibleCount,input.deputyCount,t,id);return this.getElection(id)!;}
 updateStatus(id:string,status:ElectionStatus):ElectionRecord{this.database.prepare('UPDATE sbv_elections SET status=?,updated_at=? WHERE id=?').run(status,now(),id);return this.getElection(id)!;}
 lockDeputyCount(id:string):void{this.database.prepare('UPDATE sbv_elections SET deputy_count_locked_at=COALESCE(deputy_count_locked_at,?),updated_at=? WHERE id=?').run(now(),now(),id);}
 listVoters(electionId:string):ElectionVoterRecord[]{return this.database.prepare<VoterRow>('SELECT * FROM sbv_election_voters WHERE election_id=? ORDER BY last_name COLLATE NOCASE,first_name COLLATE NOCASE').all(electionId).map(r=>({id:r.id,electionId:r.election_id,lastName:r.last_name,firstName:r.first_name,birthDate:r.birth_date_optional??undefined,orgUnit:r.org_unit??undefined,eligibilityBasis:r.eligibility_basis,eligibilityVerifiedAt:r.eligibility_verified_at??undefined,listStatus:r.list_status,createdAt:r.created_at,updatedAt:r.updated_at}));}
 saveVoter(electionId:string,input:SaveElectionVoterInput):ElectionVoterRecord{const id=input.id??randomUUID(),t=now();this.database.prepare(`INSERT INTO sbv_election_voters(id,election_id,last_name,first_name,birth_date_optional,org_unit,eligibility_basis,eligibility_verified_at,list_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET last_name=excluded.last_name,first_name=excluded.first_name,birth_date_optional=excluded.birth_date_optional,org_unit=excluded.org_unit,eligibility_basis=excluded.eligibility_basis,eligibility_verified_at=excluded.eligibility_verified_at,list_status=excluded.list_status,updated_at=excluded.updated_at`).run(id,electionId,input.lastName.trim(),input.firstName.trim(),clean(input.birthDate),clean(input.orgUnit),input.eligibilityBasis,clean(input.eligibilityVerifiedAt),input.listStatus??'draft',t,t);return this.listVoters(electionId).find(v=>v.id===id)!;}
 listBoardMembers(electionId:string):ElectionBoardMemberRecord[]{return this.database.prepare<MemberRow>('SELECT * FROM sbv_election_board_members WHERE election_id=? ORDER BY created_at').all(electionId).map(r=>({id:r.id,electionId:r.election_id,role:r.role,name:r.name,employedConfirmed:Boolean(r.employed_confirmed),adultConfirmed:Boolean(r.adult_confirmed),appointedAt:r.appointed_at??undefined,createdAt:r.created_at,updatedAt:r.updated_at}));}
 saveBoardMember(electionId:string,input:SaveElectionBoardMemberInput):ElectionBoardMemberRecord{const id=input.id??randomUUID(),t=now();this.database.prepare(`INSERT INTO sbv_election_board_members(id,election_id,role,name,employed_confirmed,adult_confirmed,appointed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET role=excluded.role,name=excluded.name,employed_confirmed=excluded.employed_confirmed,adult_confirmed=excluded.adult_confirmed,appointed_at=excluded.appointed_at,updated_at=excluded.updated_at`).run(id,electionId,input.role,input.name.trim(),input.employedConfirmed?1:0,input.adultConfirmed?1:0,clean(input.appointedAt),t,t);return this.listBoardMembers(electionId).find(v=>v.id===id)!;}
 listSessions(electionId:string):ElectionBoardSessionRecord[]{return this.database.prepare<SessionRow>('SELECT * FROM sbv_election_board_sessions WHERE election_id=? ORDER BY starts_at').all(electionId).map(r=>({id:r.id,electionId:r.election_id,startsAt:r.starts_at,participants:JSON.parse(r.participants_json) as string[],decisionsText:r.decisions_text??undefined,minutesDocumentId:r.minutes_document_id??undefined,createdAt:r.created_at,updatedAt:r.updated_at}));}
 saveSession(electionId:string,input:SaveElectionBoardSessionInput):ElectionBoardSessionRecord{const id=randomUUID(),t=now();this.database.prepare('INSERT INTO sbv_election_board_sessions(id,election_id,starts_at,participants_json,decisions_text,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,electionId,input.startsAt,JSON.stringify(input.participants),clean(input.decisionsText),t,t);return this.listSessions(electionId).find(v=>v.id===id)!;}
 setSessionDocument(id:string,documentId:string):void{this.database.prepare('UPDATE sbv_election_board_sessions SET minutes_document_id=?,updated_at=? WHERE id=?').run(documentId,now(),id);}
 listCandidates(electionId:string):ElectionCandidateRecord[]{return this.database.prepare<CandidateRow>('SELECT * FROM sbv_election_candidates WHERE election_id=? ORDER BY office_type,person_snapshot COLLATE NOCASE').all(electionId).map(r=>({id:r.id,electionId:r.election_id,officeType:r.office_type,personSnapshot:r.person_snapshot,birthDate:r.birth_date??undefined,occupation:r.occupation??undefined,consentAt:r.consent_at??undefined,eligibilityStatus:r.eligibility_status,createdAt:r.created_at,updatedAt:r.updated_at}));}
 saveCandidate(electionId:string,input:SaveElectionCandidateInput,status:string):ElectionCandidateRecord{const id=input.id??randomUUID(),t=now();this.database.prepare(`INSERT INTO sbv_election_candidates(id,election_id,office_type,person_snapshot,birth_date,occupation,consent_at,eligibility_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET office_type=excluded.office_type,person_snapshot=excluded.person_snapshot,birth_date=excluded.birth_date,occupation=excluded.occupation,consent_at=excluded.consent_at,eligibility_status=excluded.eligibility_status,updated_at=excluded.updated_at`).run(id,electionId,input.officeType,input.personSnapshot.trim(),clean(input.birthDate),clean(input.occupation),clean(input.consentAt),status,t,t);return this.listCandidates(electionId).find(v=>v.id===id)!;}
 listProposals(electionId:string):ElectionProposalRecord[]{const rows=this.database.prepare<ProposalRow>('SELECT * FROM sbv_election_proposals WHERE election_id=? ORDER BY received_at').all(electionId);return rows.map(r=>({id:r.id,electionId:r.election_id,receivedAt:r.received_at,validityStatus:r.validity_status,correctionDueAt:r.correction_due_at??undefined,invalidReason:r.invalid_reason??undefined,candidateIds:this.database.prepare<{candidate_id:string}>('SELECT candidate_id FROM sbv_election_proposal_candidates WHERE proposal_id=? ORDER BY created_at').all(r.id).map(x=>x.candidate_id),supporterVoterIds:this.database.prepare<{voter_id:string}>('SELECT voter_id FROM sbv_election_proposal_supporters WHERE proposal_id=? ORDER BY created_at').all(r.id).map(x=>x.voter_id),createdAt:r.created_at,updatedAt:r.updated_at}));}
 saveProposal(electionId:string,input:SaveElectionProposalInput,status:ProposalStatus,correctionDueAt?:string):ElectionProposalRecord{const id=input.id??randomUUID(),t=now();this.database.prepare(`INSERT INTO sbv_election_proposals(id,election_id,received_at,validity_status,correction_due_at,invalid_reason,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET received_at=excluded.received_at,validity_status=excluded.validity_status,correction_due_at=excluded.correction_due_at,invalid_reason=excluded.invalid_reason,updated_at=excluded.updated_at`).run(id,electionId,input.receivedAt,status,clean(correctionDueAt),clean(input.invalidReason),t,t);this.database.prepare('DELETE FROM sbv_election_proposal_candidates WHERE proposal_id=?').run(id);this.database.prepare('DELETE FROM sbv_election_proposal_supporters WHERE proposal_id=?').run(id);for(const candidateId of input.candidateIds??[]){const c=this.database.prepare<{office_type:OfficeType}>('SELECT office_type FROM sbv_election_candidates WHERE id=? AND election_id=?').get(candidateId,electionId);if(!c)throw new Error('Kandidatur gehört nicht zu diesem Wahlvorgang.');this.database.prepare('INSERT INTO sbv_election_proposal_candidates(id,proposal_id,candidate_id,office_type,created_at) VALUES(?,?,?,?,?)').run(randomUUID(),id,candidateId,c.office_type,t);}for(const voterId of input.supporterVoterIds??[])this.database.prepare('INSERT INTO sbv_election_proposal_supporters(id,proposal_id,voter_id,created_at) VALUES(?,?,?,?)').run(randomUUID(),id,voterId,t);return this.listProposals(electionId).find(v=>v.id===id)!;}
 listObjections(electionId:string):ElectionObjectionRecord[]{return this.database.prepare<ObjectionRow>('SELECT * FROM sbv_election_objections WHERE election_id=? ORDER BY received_at').all(electionId).map(r=>({id:r.id,electionId:r.election_id,receivedAt:r.received_at,subjectRef:r.subject_ref,decisionAt:r.decision_at??undefined,decision:r.decision??undefined,notifiedAt:r.notified_at??undefined,createdAt:r.created_at,updatedAt:r.updated_at}));}
 saveObjection(electionId:string,input:SaveElectionObjectionInput):ElectionObjectionRecord{const id=input.id??randomUUID(),t=now();this.database.prepare(`INSERT INTO sbv_election_objections(id,election_id,received_at,subject_ref,decision_at,decision,notified_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET received_at=excluded.received_at,subject_ref=excluded.subject_ref,decision_at=excluded.decision_at,decision=excluded.decision,notified_at=excluded.notified_at,updated_at=excluded.updated_at`).run(id,electionId,input.receivedAt,input.subjectRef.trim(),clean(input.decisionAt),clean(input.decision),clean(input.notifiedAt),t,t);return this.listObjections(electionId).find(v=>v.id===id)!;}
}
