import type { DatabaseAdapter } from './databaseService.js';
import { SbvOfficeWorkflowDocumentAdapter, type SbvOfficeDocumentRecord } from './sbvOfficeWorkflowDocumentAdapter.js';
import { ElectionPreparationRepository } from './electionPreparationRepository.js';
import { createSimpleTextPdf } from './documents/simpleTextPdf.js';
import type { ElectionNoticeDetails, ElectionRecord, GenerateElectionPreparationDocumentInput } from '../src/app/core/models/election-workflow.model.js';
const TEMPLATE_VERSION='0.9.7-C.1';
function noticeFields(n:ElectionNoticeDetails):[string,string][]{return[['Erlassdatum',n.issueDate],['Beginn Stimmabgabe',n.votingStartsAt],['Ende Stimmabgabe',n.votingEndsAt],['Wahlort',n.votingPlace],['Auszaehlung',n.countingPlaceAndTime],['Einsicht Waehlerliste',n.voterListInspectionPlace],['Einsichtzeiten',n.voterListInspectionTimes],['Einspruchsfrist',n.objectionDeadline],['Vorschlagsfrist',n.proposalDeadline],['Einreichungsort',n.proposalSubmissionPlace],['Vertrauensperson',n.representativeElectionStatement],['Stellvertretungen',n.deputyElectionStatement],['Stuetzunterschriften',n.requiredSupportSignatures],['Briefwahl',n.mailBallotStatement],['Vorsitz Wahlvorstand',n.boardChairName],['Weiteres Mitglied',n.secondBoardMemberName]];}
export function validateElectionNoticeDetails(n:ElectionNoticeDetails|undefined):ElectionNoticeDetails{if(!n)throw new Error('Wahlausschreiben benötigt die 16 Pflichtangaben.');const missing=noticeFields(n).filter(([,v])=>!v.trim()).map(([k])=>k);if(missing.length)throw new Error(`Wahlausschreiben unvollständig: ${missing.join(', ')}.`);return n;}
export class SbvElectionDocumentService{
 private readonly repo:ElectionPreparationRepository;
 constructor(db:DatabaseAdapter,private readonly documents:SbvOfficeWorkflowDocumentAdapter){this.repo=new ElectionPreparationRepository(db);}
 async generate(electionId:string,input:GenerateElectionPreparationDocumentInput):Promise<SbvOfficeDocumentRecord>{const election=this.repo.getElection(electionId);if(!election)throw new Error('Wahlvorgang wurde nicht gefunden.');const title=input.titleOverride?.trim()||this.title(input.kind);const plain=createSimpleTextPdf(title,this.lines(input,election));const record=await this.documents.store({owner:{type:'election',id:electionId},title,filename:`${input.kind}-${electionId.slice(0,8)}.pdf`,mimeType:'application/pdf',purpose:input.kind,documentClass:'generated_document',templateVersion:TEMPLATE_VERSION,legalRuleVersion:election.legalRuleVersion,plain});if(input.kind==='board_minutes'&&input.boardSessionId)this.repo.setSessionDocument(input.boardSessionId,record.id);return record;}
 private title(kind:GenerateElectionPreparationDocumentInput['kind']):string{return({setup_summary:'Wahl-Setup',board_appointment:'Bestellung Wahlvorstand',board_minutes:'Niederschrift Wahlvorstand',voter_list:'Wählerliste',election_notice:'Wahlausschreiben',proposal_correction_notice:'Aufforderung zur Korrektur',proposal_grace_notice:'Nachfrist Wahlvorschläge',candidate_announcement:'Bekanntmachung Kandidaturen',simplified_invitation:'Einladung Wahlversammlung',election_leadership_minutes:'Niederschrift Wahlleitung'} as const)[kind];}
 private lines(input:GenerateElectionPreparationDocumentInput,e:ElectionRecord):string[]{const id=e.id,head=[`Wahl-ID: ${id}`,`Verfahren: ${e.procedure??'noch nicht bestaetigt'}`,`Rechtsregel: ${e.legalRuleVersion}`],voters=this.repo.listVoters(id),members=this.repo.listBoardMembers(id),candidates=this.repo.listCandidates(id);switch(input.kind){case'setup_summary':return[...head,`Wahlart: ${e.kind}`,`Wahlberechtigte Snapshot: ${e.eligibleCountSnapshot}`,`Mindestschwelle: ${e.minimumThresholdMet?'erfuellt':'nicht erfuellt'}`,`Raeumlich getrennte Betriebsteile: ${e.spatiallySeparated?'ja':'nein'}`];case'board_appointment':return[...head,...members.map(m=>`${m.role}: ${m.name} | volljaehrig ${m.adultConfirmed?'ja':'nein'} | beschaeftigt ${m.employedConfirmed?'ja':'nein'}`)];case'board_minutes':{const s=input.boardSessionId?this.repo.listSessions(id).find(x=>x.id===input.boardSessionId):undefined;if(!s)throw new Error('Niederschrift benötigt eine Wahlvorstandssitzung.');return[...head,`Sitzung: ${s.startsAt}`,`Teilnehmende: ${s.participants.join(', ')}`,`Beschluesse: ${s.decisionsText??'-'}`];}case'voter_list':return[...head,'Alphabetische Waehlerliste',...voters.filter(v=>v.listStatus==='eligible').map(v=>`${v.lastName}, ${v.firstName}${v.birthDate?` | ${v.birthDate}`:''}${v.orgUnit?` | ${v.orgUnit}`:''}`),'Keine GdB-Werte oder Statusbegruendungen enthalten.'];case'election_notice':{if(e.procedure!=='formal')throw new Error('Wahlausschreiben gehört zum förmlichen Verfahren.');const n=validateElectionNoticeDetails(input.notice);return[...head,...noticeFields(n).map(([k,v],i)=>`${i+1}. ${k}: ${v}`)];}case'candidate_announcement':return[...head,'Vertrauensperson',...candidates.filter(c=>c.officeType==='representative').map(c=>c.personSnapshot).sort((a,b)=>a.localeCompare(b,'de')),'Stellvertretung',...candidates.filter(c=>c.officeType==='deputy').map(c=>c.personSnapshot).sort((a,b)=>a.localeCompare(b,'de'))];case'simplified_invitation':if(e.procedure!=='simplified')throw new Error('Einladung zur Wahlversammlung gehört zum vereinfachten Verfahren.');return[...head,'Einladung zur Wahlversammlung','Wahlzweck: Wahl der Schwerbehindertenvertretung',`Termin: ${e.electionDate??'noch einzutragen'}`];case'election_leadership_minutes':return[...head,...members.filter(m=>['election_leader','assistant'].includes(m.role)).map(m=>`${m.role}: ${m.name}`),'Es werden nur Ergebnisse der Wahlleitung dokumentiert, keine Einzelstimmen.'];case'proposal_correction_notice':return[...head,'Klaerungs-/Korrekturaufforderung','Frist: drei Arbeitstage gemaess gespeicherter zentraler Frist.'];case'proposal_grace_notice':return[...head,'Nachfrist fuer Wahlvorschlaege','Frist: eine Woche gemaess gespeicherter zentraler Frist.'];}}
}
