import { randomUUID } from 'node:crypto';
import type { DatabaseAdapter } from './databaseService.js';
import { DatabaseUnitOfWork } from './databaseUnitOfWork.js';
import { PersonalDataAuditLogService } from './auditLogService.js';
import { DeadlineService } from './deadlineService.js';
import { ElectionDeadlinePolicy } from './electionDeadlinePolicy.js';
import { ElectionLegalPolicy } from './electionLegalPolicy.js';
import { ElectionPreparationRepository } from './electionPreparationRepository.js';
import { buildFromContext } from './activityJournalPrefill.js';
import type { ActivityJournalPrefill } from '../src/app/core/models/activity-journal.model.js';
import { ELECTION_LEGAL_RULE_VERSION, type ElectionDeadlineRuleKey, type EligibilityBasis, type ProposalStatus } from '../src/app/core/models/election.model.js';
import type { ConfigureElectionSetupInput, CreateElectionInput, ElectionBoardMemberRecord, ElectionBoardSessionRecord, ElectionCandidateRecord, ElectionObjectionRecord, ElectionPreparationOverview, ElectionProposalRecord, ElectionRecord, ElectionSetupAssessment, ElectionVoterRecord, SaveElectionBoardMemberInput, SaveElectionBoardSessionInput, SaveElectionCandidateInput, SaveElectionObjectionInput, SaveElectionProposalInput, SaveElectionVoterInput } from '../src/app/core/models/election-workflow.model.js';

const isoNoon=(date:string)=>`${date.slice(0,10)}T12:00:00.000Z`;
function trimmed(value:string|undefined,label:string):string|undefined{if(value===undefined)return undefined;const v=value.trim();if(!v)throw new Error(`${label} darf nicht leer sein.`);return v;}
function assertCount(value:number,label:string):void{if(!Number.isInteger(value)||value<0)throw new Error(`${label} muss eine nichtnegative ganze Zahl sein.`);}
function eligibilityBases(input:ConfigureElectionSetupInput):EligibilityBasis[]{return [...Array(input.confirmedSeverelyDisabledCount).fill('severely_disabled_confirmed'),...Array(input.confirmedEqualizedCount).fill('equalized_confirmed'),...Array(input.pendingEqualizationCount??0).fill('pending_equalization_not_eligible')] as EligibilityBasis[];}

export class SbvElectionService{
 private readonly repo:ElectionPreparationRepository;
 constructor(private readonly db:DatabaseAdapter,private readonly deadlines=new DeadlineService(db),private readonly audit=new PersonalDataAuditLogService(db),private readonly legal=new ElectionLegalPolicy(),private readonly deadlinePolicy=new ElectionDeadlinePolicy()){this.repo=new ElectionPreparationRepository(db);}
 list():ElectionRecord[]{return this.repo.listElections();}
 get(id:string):ElectionRecord{const e=this.repo.getElection(id);if(!e)throw new Error('Wahlvorgang wurde nicht gefunden.');return e;}
 create(input:CreateElectionInput):ElectionRecord{
  const reason=trimmed(input.triggerReason,'Wahlgrund');
  if(input.kind!=='regular'&&!reason)throw new Error('Außerordentliche Wahlen benötigen einen dokumentierten Wahlgrund.');
  if(input.kind==='regular'&&input.electionDate&&!this.legal.isRegularElectionDate(input.electionDate))throw new Error('Regelwahl liegt außerhalb des gesetzlichen Wahlzeitraums.');
  const next=input.officeTermStart&&input.kind!=='regular'?this.legal.calculateNextRegularElectionPeriod(input.officeTermStart):undefined;
  return new DatabaseUnitOfWork(this.db).run(()=>{const election=this.repo.insertElection({id:randomUUID(),kind:input.kind,triggerReason:reason,electionDate:input.electionDate,incumbentTermEnd:input.incumbentTermEnd,officeTermStart:input.officeTermStart,officeTermEnd:input.kind==='deputy_by_election'?(input.incumbentTermEnd??input.officeTermEnd):input.officeTermEnd,nextRegularElectionPeriod:next?`${next.startsOn}/${next.endsOn}`:undefined,legalRuleVersion:ELECTION_LEGAL_RULE_VERSION});this.auditMutation('create',election.id,{entityType:'election',status:election.status});return election;});
 }
 configureSetup(id:string,input:ConfigureElectionSetupInput):ElectionSetupAssessment{
  const election=this.get(id);assertCount(input.confirmedSeverelyDisabledCount,'Bestätigte schwerbehinderte Beschäftigte');assertCount(input.confirmedEqualizedCount,'Bestätigte gleichgestellte Beschäftigte');assertCount(input.pendingEqualizationCount??0,'Offene Gleichstellungsanträge');
  const threshold=this.legal.assessMinimumThreshold(eligibilityBases(input));const suggestion=this.legal.suggestProcedure(threshold.eligibleCount,input.spatiallySeparated);const selected=input.procedure??suggestion.suggestedProcedure;
  const deputyCount=input.deputyCount??election.deputyCount;if(!Number.isInteger(deputyCount)||deputyCount<1)throw new Error('Anzahl der Stellvertretungen muss mindestens 1 sein.');if(election.deputyCountLockedAt&&deputyCount!==election.deputyCount)throw new Error('Anzahl der Stellvertretungen ist nach Beginn der Kandidaturen fixiert.');
  const date=input.electionDate??election.electionDate;const regularValid=election.kind!=='regular'||Boolean(date&&this.legal.isRegularElectionDate(date));const ready=threshold.thresholdMet&&regularValid;
  const basis=JSON.stringify({checkDate:input.eligibilityCheckDate,confirmedSeverelyDisabledCount:input.confirmedSeverelyDisabledCount,confirmedEqualizedCount:input.confirmedEqualizedCount,pendingEqualizationCount:input.pendingEqualizationCount??0,legalRuleVersion:ELECTION_LEGAL_RULE_VERSION});
  new DatabaseUnitOfWork(this.db).run(()=>{this.repo.updateSetup(id,{procedure:selected,procedureDecisionNote:input.procedureDecisionNote,status:ready?'procedure_confirmed':'draft',electionDate:date,eligibilityCheckDate:input.eligibilityCheckDate,eligibleCount:threshold.eligibleCount,thresholdMet:threshold.thresholdMet,basisJson:basis,spatiallySeparated:input.spatiallySeparated,deputyCount});if(ready)this.ensurePreparationDeadlines(this.get(id));this.auditMutation('update',id,{entityType:'setup',status:ready?'ready':'conflict',procedure:selected});});
  return{eligibleCountSnapshot:threshold.eligibleCount,minimumThresholdMet:threshold.thresholdMet,suggestedProcedure:suggestion.suggestedProcedure,selectedProcedure:selected,procedureDiffersFromSuggestion:selected!==suggestion.suggestedProcedure,regularElectionDateValid:regularValid,startReady:ready,legalRuleVersion:ELECTION_LEGAL_RULE_VERSION};
 }
 overview(id:string):ElectionPreparationOverview{const election=this.get(id),boardMembers=this.repo.listBoardMembers(id);const conflicts:string[]=[];if(!election.minimumThresholdMet)conflicts.push('Mindestschwelle von fünf bestätigten Wahlberechtigten ist nicht erfüllt.');if(!election.procedure)conflicts.push('Wahlverfahren ist noch nicht bestätigt.');if(election.kind==='regular'&&(!election.electionDate||!this.legal.isRegularElectionDate(election.electionDate)))conflicts.push('Regelwahl benötigt einen Wahltag im gesetzlichen Regelwahlzeitraum.');if(election.procedure==='formal'){const active=boardMembers.filter(m=>m.role==='chair'||m.role==='member');const chairs=active.filter(m=>m.role==='chair');if(active.length<3||chairs.length!==1||active.some(m=>!m.adultConfirmed||!m.employedConfirmed))conflicts.push('Förmlicher Wahlvorstand benötigt genau einen Vorsitz und insgesamt drei bestätigte volljährige Beschäftigte.');const chair=chairs[0];if(chair?.appointedAt&&election.electionDate){const target=this.deadlinePolicy.calculate('formal.election.target',chair.appointedAt,{incumbentTermEnd:election.incumbentTermEnd});if(election.electionDate.slice(0,10)>target.dueOn)conflicts.push('Wahltermin überschreitet das Ziel für die unverzügliche Wahleinleitung.');}}if(election.procedure==='simplified'&&!boardMembers.some(m=>m.role==='election_leader'))conflicts.push('Wahlleitung der Wahlversammlung ist noch nicht dokumentiert.');return{election,voters:this.repo.listVoters(id),boardMembers,boardSessions:this.repo.listSessions(id),candidates:this.repo.listCandidates(id),proposals:this.repo.listProposals(id),objections:this.repo.listObjections(id),conflicts};}
 saveVoter(id:string,input:SaveElectionVoterInput):ElectionVoterRecord{this.get(id);if(!input.lastName.trim()||!input.firstName.trim())throw new Error('Wählerlisteneintrag benötigt Name und Vorname.');const eligible=input.eligibilityBasis==='severely_disabled_confirmed'||input.eligibilityBasis==='equalized_confirmed';const normalized={...input,listStatus:eligible?(input.listStatus??'eligible'):'not_eligible'};return new DatabaseUnitOfWork(this.db).run(()=>{const value=this.repo.saveVoter(id,normalized);this.auditMutation('update',id,{entityType:'voter',status:value.listStatus});return value;});}
 saveBoardMember(id:string,input:SaveElectionBoardMemberInput):ElectionBoardMemberRecord{const e=this.get(id);const allowed=e.procedure==='simplified'?['election_leader','assistant']:['chair','member','substitute'];if(!e.procedure||!allowed.includes(input.role))throw new Error('Rolle passt nicht zum bestätigten Wahlverfahren.');if(!input.name.trim())throw new Error('Wahlorgan-Mitglied benötigt einen Namen.');return new DatabaseUnitOfWork(this.db).run(()=>{const value=this.repo.saveBoardMember(id,input);if(e.procedure==='formal'&&input.role==='chair'&&input.appointedAt){const due=this.deadlinePolicy.calculate('formal.election.target',input.appointedAt,{incumbentTermEnd:e.incumbentTermEnd});this.ensureDeadline(id,'formal.election.target',input.appointedAt,due.dueOn,due.legalReference,'Förmliche Wahl unverzüglich einleiten');}this.auditMutation('update',id,{entityType:'election_body',status:input.role});return value;});}
 saveBoardSession(id:string,input:SaveElectionBoardSessionInput):ElectionBoardSessionRecord{const e=this.get(id);if(e.procedure!=='formal')throw new Error('Wahlvorstandssitzungen gehören zum förmlichen Verfahren.');if(!input.participants.length)throw new Error('Sitzung benötigt Teilnehmende.');return new DatabaseUnitOfWork(this.db).run(()=>{const value=this.repo.saveSession(id,input);this.auditMutation('update',id,{entityType:'board_session',status:'recorded'});return value;});}
 saveObjection(id:string,input:SaveElectionObjectionInput):ElectionObjectionRecord{if(this.get(id).procedure!=='formal')throw new Error('Wählerlisteneinsprüche werden im förmlichen Verfahren geführt.');if(!input.subjectRef.trim())throw new Error('Einspruch benötigt einen Bezug.');return new DatabaseUnitOfWork(this.db).run(()=>{const value=this.repo.saveObjection(id,input);this.auditMutation('update',id,{entityType:'voter_objection',status:value.notifiedAt?'closed':'open'});return value;});}
 saveCandidate(id:string,input:SaveElectionCandidateInput):ElectionCandidateRecord{const e=this.get(id);if(!e.procedure)throw new Error('Wahlverfahren muss vor Kandidaturen bestätigt sein.');if(!input.personSnapshot.trim())throw new Error('Kandidatur benötigt eine Person.');const assessment=this.legal.assessCandidateEligibility(input);return new DatabaseUnitOfWork(this.db).run(()=>{const value=this.repo.saveCandidate(id,input,assessment.eligible?'policy_eligible':'policy_conflict');this.repo.lockDeputyCount(id);this.auditMutation('update',id,{entityType:'candidate',officeType:input.officeType,result:assessment.eligible?'criteria_met':'criteria_conflict'});return value;});}
 saveProposal(id:string,input:SaveElectionProposalInput):ElectionProposalRecord{const e=this.get(id);if(e.procedure!=='formal')throw new Error('Schriftliche Wahlvorschläge gehören zum förmlichen Verfahren.');const candidateIds=[...new Set(input.candidateIds??[])],supporterIds=[...new Set(input.supporterVoterIds??[])];const candidates=this.repo.listCandidates(id);if(candidateIds.some(cid=>!candidates.some(c=>c.id===cid)))throw new Error('Wahlvorschlag enthält eine fremde Kandidatur.');const eligibleSupporters=new Set(this.repo.listVoters(id).filter(v=>v.listStatus==='eligible').map(v=>v.id));if(supporterIds.some(v=>!eligibleSupporters.has(v)))throw new Error('Stützunterschrift stammt nicht aus der bestätigten Wählerliste.');const required=this.legal.requiredSupportSignatures(e.eligibleCountSnapshot);let status:ProposalStatus=input.validityStatus??'received';if(status==='valid'&&(candidateIds.length===0||supporterIds.length<required))status='received';const existing=this.repo.listProposals(id).filter(p=>p.id!==input.id);const duplicateCandidate=candidateIds.some(candidateId=>existing.some(p=>p.candidateIds.includes(candidateId)));const duplicateSupporter=supporterIds.some(voterId=>existing.some(p=>p.supporterVoterIds.includes(voterId)));const correctionRequired=duplicateCandidate||duplicateSupporter;let correctionDue=input.correctionDueAt;if(correctionRequired){status='correction_required';const snap=this.deadlinePolicy.calculate('formal.proposal.correction',input.receivedAt);correctionDue=snap.dueOn;}
  return new DatabaseUnitOfWork(this.db).run(()=>{const value=this.repo.saveProposal(id,{...input,candidateIds,supporterVoterIds:supporterIds,invalidReason:correctionRequired?(duplicateCandidate&&duplicateSupporter?'candidate_and_supporter_duplicate':duplicateCandidate?'candidate_duplicate':'supporter_duplicate'):input.invalidReason},status,correctionDue);if(correctionRequired&&correctionDue)this.ensureDeadline(id,'formal.proposal.correction',input.receivedAt,correctionDue,'§ 6 Abs. 3 und 4 SchwbVWO',duplicateSupporter?'Mehrfachunterstützung klären':'Doppelbenennung klären');this.repo.updateStatus(id,'nominations');this.auditMutation('update',id,{entityType:'proposal',status:value.validityStatus});return value;});}
 startGracePeriod(id:string,sourceDate:string):ElectionProposalRecord{if(this.get(id).procedure!=='formal')throw new Error('Nachfrist gehört zum förmlichen Verfahren.');const snap=this.deadlinePolicy.calculate('formal.proposal.grace',sourceDate);return new DatabaseUnitOfWork(this.db).run(()=>{const value=this.repo.saveProposal(id,{receivedAt:sourceDate,validityStatus:'grace_period'},'grace_period',snap.dueOn);this.ensureDeadline(id,'formal.proposal.grace',sourceDate,snap.dueOn,snap.legalReference,'Nachfrist Wahlvorschläge');this.auditMutation('update',id,{entityType:'proposal_grace',status:'open'});return value;});}
 recordElectionNoticeIssued(id:string,issueDate:string):void{const e=this.get(id);if(e.procedure!=='formal')throw new Error('Wahlausschreiben gehört zum förmlichen Verfahren.');new DatabaseUnitOfWork(this.db).run(()=>{for(const key of ['formal.voterlist.objection','formal.proposal.submit'] as const){const snap=this.deadlinePolicy.calculate(key,issueDate);this.ensureDeadline(id,key,issueDate,snap.dueOn,snap.legalReference,key==='formal.voterlist.objection'?'Einspruchsfrist Wählerliste':'Frist Wahlvorschläge');}this.auditMutation('update',id,{entityType:'election_notice',status:'issued'});});}
 markPreparation(id:string):ElectionRecord{const overview=this.overview(id);if(overview.conflicts.length)throw new Error(overview.conflicts.join(' '));return new DatabaseUnitOfWork(this.db).run(()=>{const value=this.repo.updateStatus(id,'preparation');this.auditMutation('update',id,{entityType:'election',status:'preparation'});return value;});}
 journalPrefill(id:string,activity:'preparation'|'board_work'|'voter_list'|'nominations'|'voting'|'counting'|'result'|'archive'):ActivityJournalPrefill{this.get(id);return buildFromContext({contextType:'fallfrei',title:`SBV-Wahl: ${activity}`,category:'committee_work',entryDate:new Date().toISOString().slice(0,10)});}
 private ensurePreparationDeadlines(e:ElectionRecord):void{if(e.procedure==='formal'&&e.incumbentTermEnd){const board=this.deadlinePolicy.calculate('formal.board.appoint',e.incumbentTermEnd);this.ensureDeadline(e.id,'formal.board.appoint',e.incumbentTermEnd,board.dueOn,board.legalReference,'Wahlvorstand bestellen');}if(!e.electionDate)return;if(e.procedure==='formal'){for(const key of ['formal.notice.publish','formal.candidates.publish'] as const){const snap=this.deadlinePolicy.calculate(key,e.electionDate);this.ensureDeadline(e.id,key,e.electionDate,snap.dueOn,snap.legalReference,key==='formal.notice.publish'?'Wahlausschreiben erlassen':'Kandidaturen bekanntmachen');}}else if(e.procedure==='simplified'&&e.incumbentTermEnd){const snap=this.deadlinePolicy.calculate('simplified.invitation',e.incumbentTermEnd);this.ensureDeadline(e.id,'simplified.invitation',e.incumbentTermEnd,snap.dueOn,snap.legalReference,'Zur Wahlversammlung einladen');}}
 private ensureDeadline(electionId:string,key:ElectionDeadlineRuleKey,sourceDate:string,dueOn:string,legalBasis:string,title:string):void{const exists=this.db.prepare<{id:string}>("SELECT id FROM deadlines WHERE process_type='election' AND process_id=? AND source_event=? AND status IN ('open','overdue') LIMIT 1").get(electionId,key);if(exists)return;const created=this.deadlines.create({processId:electionId,processType:'election',deadlineType:'legal_deadline',title,dueAt:isoNoon(dueOn),legalBasis,sourceEvent:key,severity:'important',calculationMode:'legal',isLegalDeadline:true});this.db.prepare('UPDATE deadlines SET rule_key=?,source_date=?,legal_rule_version=?,original_due_at=? WHERE id=?').run(key,sourceDate.slice(0,10),ELECTION_LEGAL_RULE_VERSION,isoNoon(dueOn),created.id);}
 private auditMutation(action:'create'|'update',subjectId:string,metadata:Record<string,unknown>):void{this.audit.append({action,subjectType:'election',subjectId,purpose:'SBV-Wahlvorbereitung dokumentiert',metadata});}
}
