import { randomUUID } from 'node:crypto';
import type { DatabaseAdapter } from './databaseService.js';
import { DatabaseUnitOfWork } from './databaseUnitOfWork.js';
import { DeadlineService } from './deadlineService.js';
import type { PersonalDataAuditLogService } from './auditLogService.js';
import { buildFromContext } from './activityJournalPrefill.js';
import type { ActivityJournalPrefill } from '../src/domain/models/activity-journal.model.js';
import type { CreateSbvMeetingInput, SbvMeetingAgendaItemRecord, SbvMeetingRecord, UpdateSbvMeetingInput, UpsertSbvMeetingAgendaInput } from '../src/domain/models/sbv-office-workflow.model.js';
import { calculateSbvMeetingSuspensionDueAt } from './sbvMeetingPolicy.js';

const iso=()=>new Date().toISOString();
const opt=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null;
interface MeetingRow { id:string; meeting_type:SbvMeetingRecord['meetingType']; title:string; starts_at:string; location:string|null; invitation_received_at:string|null; agenda_received_at:string|null; attendance_status:string; status:SbvMeetingRecord['status']; notes:string|null; created_at:string; updated_at:string; }
interface AgendaRow { id:string;meeting_id:string;position:number;title:string;sbv_relevance:number;reference_scope:string|null;documents_status:string|null;own_position:string|null;requested_by_sbv:number;request_at:string|null;request_content:string|null;request_reaction:string|null;resolution_at:string|null;resolution_summary:string|null;impairment_assessment:string|null;significant_impairment:number;non_participation:number;suspension_requested_at:string|null;suspension_due_at:string|null;outcome:string|null;status:string; }
function agendaMap(r:AgendaRow):SbvMeetingAgendaItemRecord{return{id:r.id,meetingId:r.meeting_id,position:r.position,title:r.title,sbvRelevance:!!r.sbv_relevance,referenceScope:r.reference_scope??undefined,documentsStatus:r.documents_status??undefined,ownPosition:r.own_position??undefined,requestedBySbv:!!r.requested_by_sbv,requestAt:r.request_at??undefined,requestContent:r.request_content??undefined,requestReaction:r.request_reaction??undefined,resolutionAt:r.resolution_at??undefined,resolutionSummary:r.resolution_summary??undefined,impairmentAssessment:r.impairment_assessment??undefined,significantImpairment:!!r.significant_impairment,nonParticipation:!!r.non_participation,suspensionRequestedAt:r.suspension_requested_at??undefined,suspensionDueAt:r.suspension_due_at??undefined,outcome:r.outcome??undefined,status:r.status};}
export class SbvMeetingService {
 constructor(private db:DatabaseAdapter, private deadlines:DeadlineService=new DeadlineService(db), private audit?:PersonalDataAuditLogService){}
 private agenda(id:string){return this.db.prepare<AgendaRow>('SELECT * FROM sbv_meeting_agenda_items WHERE meeting_id=? ORDER BY position,id').all(id).map(agendaMap);}
 list():SbvMeetingRecord[]{return this.db.prepare<MeetingRow>('SELECT * FROM sbv_meetings ORDER BY starts_at DESC').all().map(r=>({id:r.id,meetingType:r.meeting_type,title:r.title,startsAt:r.starts_at,location:r.location??undefined,invitationReceivedAt:r.invitation_received_at??undefined,agendaReceivedAt:r.agenda_received_at??undefined,attendanceStatus:r.attendance_status,status:r.status,notes:r.notes??undefined,createdAt:r.created_at,updatedAt:r.updated_at,agenda:this.agenda(r.id)}));}
 create(input:CreateSbvMeetingInput):SbvMeetingRecord{return new DatabaseUnitOfWork(this.db).run(()=>{if(!input.title?.trim()||!input.startsAt)throw new Error('Sitzung benötigt Titel und Datum/Zeit.');const id=randomUUID(),t=iso();this.db.prepare('INSERT INTO sbv_meetings(id,meeting_type,title,starts_at,location,attendance_status,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,input.meetingType,input.title.trim(),input.startsAt,opt(input.location),'planned',input.status??'draft',t,t);if(this.audit) this.audit.append({action:'create',subjectType:'sbv_meeting',subjectId:id,purpose:'SBV-Sitzung anlegen'});return this.list().find(x=>x.id===id)!;});}
 update(id:string,input:UpdateSbvMeetingInput):SbvMeetingRecord{return new DatabaseUnitOfWork(this.db).run(()=>{const cur=this.list().find(x=>x.id===id);if(!cur)throw new Error('Sitzung nicht gefunden.');this.db.prepare('UPDATE sbv_meetings SET meeting_type=?,title=?,starts_at=?,location=?,invitation_received_at=?,agenda_received_at=?,attendance_status=?,status=?,notes=?,updated_at=? WHERE id=?').run(input.meetingType??cur.meetingType,(input.title??cur.title).trim(),input.startsAt??cur.startsAt,opt(input.location??cur.location),opt(input.invitationReceivedAt??cur.invitationReceivedAt),opt(input.agendaReceivedAt??cur.agendaReceivedAt),input.attendanceStatus??cur.attendanceStatus,input.status??cur.status,opt(input.notes??cur.notes),iso(),id);if(this.audit) this.audit.append({action:'update',subjectType:'sbv_meeting',subjectId:id,purpose:'SBV-Sitzung aktualisieren'});return this.list().find(x=>x.id===id)!;});}
 journalPrefill(meetingId:string,activity:'attendance'|'preparation'|'top_request'|'suspension'):ActivityJournalPrefill{
  const meeting=this.list().find(x=>x.id===meetingId);
  if(!meeting)throw new Error('Sitzung nicht gefunden.');
  const title:Record<typeof activity,string>={attendance:`Teilnahme: ${meeting.title}`,preparation:`Vorbereitung: ${meeting.title}`,top_request:`TOP-Antrag: ${meeting.title}`,suspension:`Aussetzung: ${meeting.title}`};
  return buildFromContext({contextType:'fallfrei',title:title[activity],category:activity==='attendance'||activity==='preparation'?'committee_work':'sbv_steering'});
 }

 createAgendaFollowUp(agendaId:string,dueAt:string,title='TOP-Antrag nachhalten'){
  const row=this.db.prepare<{meeting_id:string}>('SELECT meeting_id FROM sbv_meeting_agenda_items WHERE id=?').get(agendaId);
  if(!row)throw new Error('Tagesordnungspunkt nicht gefunden.');
  return this.deadlines.create({processId:agendaId,processType:'sbv_meeting',deadlineType:'follow_up',title,dueAt,legalBasis:'§ 178 Abs. 4 Satz 1 SGB IX',severity:'important',calculationMode:'workflow',isLegalDeadline:false,sourceEvent:'sbv_meeting_top_follow_up'});
 }

 upsertAgenda(meetingId:string,input:UpsertSbvMeetingAgendaInput):SbvMeetingAgendaItemRecord{return new DatabaseUnitOfWork(this.db).run(()=>{if(!input.title?.trim())throw new Error('Tagesordnungspunkt benötigt einen Titel.');const existing=input.id?this.agenda(meetingId).find(x=>x.id===input.id):undefined;const id=existing?.id??randomUUID(),t=iso(),position=input.position??existing?.position??this.agenda(meetingId).length+1;const significant=input.significantImpairment??existing?.significantImpairment??false,nonParticipation=input.nonParticipation??existing?.nonParticipation??false;const resolutionAt=input.resolutionAt??existing?.resolutionAt;let suspensionDueAt=input.suspensionDueAt??existing?.suspensionDueAt;if((significant||nonParticipation)&&input.suspensionRequestedAt&&resolutionAt&&!suspensionDueAt){suspensionDueAt=calculateSbvMeetingSuspensionDueAt(resolutionAt);}
 const referenceScope=input.referenceScope??existing?.referenceScope??'none';
 const values=[position,input.title.trim(),(input.sbvRelevance??existing?.sbvRelevance??false)?1:0,referenceScope,opt(input.documentsStatus??existing?.documentsStatus),opt(input.ownPosition??existing?.ownPosition),(input.requestedBySbv??existing?.requestedBySbv??false)?1:0,opt(input.requestAt??existing?.requestAt),opt(input.requestContent??existing?.requestContent),opt(input.requestReaction??existing?.requestReaction),opt(resolutionAt),opt(input.resolutionSummary??existing?.resolutionSummary),opt(input.impairmentAssessment??existing?.impairmentAssessment),significant?1:0,nonParticipation?1:0,opt(input.suspensionRequestedAt??existing?.suspensionRequestedAt),opt(suspensionDueAt),opt(input.outcome??existing?.outcome),input.status??existing?.status??'open',t];
 if(existing)this.db.prepare('UPDATE sbv_meeting_agenda_items SET position=?,title=?,sbv_relevance=?,reference_scope=?,documents_status=?,own_position=?,requested_by_sbv=?,request_at=?,request_content=?,request_reaction=?,resolution_at=?,resolution_summary=?,impairment_assessment=?,significant_impairment=?,non_participation=?,suspension_requested_at=?,suspension_due_at=?,outcome=?,status=?,updated_at=? WHERE id=?').run(...values,id);
 else this.db.prepare('INSERT INTO sbv_meeting_agenda_items(position,title,sbv_relevance,reference_scope,documents_status,own_position,requested_by_sbv,request_at,request_content,request_reaction,resolution_at,resolution_summary,impairment_assessment,significant_impairment,non_participation,suspension_requested_at,suspension_due_at,outcome,status,updated_at,id,meeting_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...values,id,meetingId,t);
 if(suspensionDueAt&&input.suspensionRequestedAt){const present=this.db.prepare<{id:string}>("SELECT id FROM deadlines WHERE process_type='sbv_meeting' AND process_id=? AND source_event='Beschlussfassung' AND status!='cancelled'").get(id);if(!present)this.deadlines.create({processId:id,processType:'sbv_meeting',deadlineType:'legal_deadline',title:'Aussetzungsfrist SBV',dueAt:suspensionDueAt,legalBasis:'§ 178 Abs. 4 Satz 2 SGB IX',severity:'critical',calculationMode:'legal',isLegalDeadline:true,isUserEditable:false,sourceEvent:'Beschlussfassung'});}
 if(this.audit) this.audit.append({action:existing?'update':'create',subjectType:'sbv_meeting',subjectId:meetingId,purpose:'SBV-Tagesordnung dokumentieren'});return this.agenda(meetingId).find(x=>x.id===id)!;});}
}
