import { test, expect } from './support/isolatedTest';

test('legt Vorlagen an, bearbeitet sie und löscht sie nur nach bewusster Bestätigung', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('navigation', { name: 'Hauptnavigation' }).waitFor();
  await page.getByRole('navigation', { name: 'Hauptnavigation' }).getByRole('button', { name: 'Vorlagen', exact: true }).click();
  const region = page.getByLabel('Vorlagen', { exact: true });
  const status = page.locator('.industrial-live-region[role="status"]');
  await region.getByRole('button', { name: 'Neue Vorlage', exact: true }).click();
  const createDialog = page.getByRole('dialog', { name: 'Vorlage ergänzen', exact: true });
  await expect(createDialog.getByRole('textbox', { name: 'Titel', exact: true })).toBeFocused();
  await createDialog.getByRole('textbox', { name: 'Titel', exact: true }).fill('Synthetische Qualitätsvorlage');
  await createDialog.getByLabel('Betreff', { exact: true }).fill('Ärztliche Anhörung');
  await createDialog.getByRole('textbox', { name: 'Text', exact: true }).fill('Überprüfung ohne Echtdaten.');
  await createDialog.getByLabel('Normen', { exact: true }).fill('§ 178, § 178, § 167');
  await createDialog.getByRole('button', { name: 'Vorlage speichern', exact: true }).focus();
  await page.keyboard.press('Enter');
  await expect(createDialog).not.toBeVisible();
  await expect(status).toHaveText('Eigene Vorlage wurde gespeichert.');
  const detail = region.locator('.template-detail-panel');
  await expect(detail.getByRole('heading', { name: 'Synthetische Qualitätsvorlage', exact: true })).toBeVisible();
  await expect(detail).toContainText('§ 178, § 167');
  await expect(detail).toContainText('Überprüfung ohne Echtdaten.');
  await detail.getByRole('button', { name: 'Bearbeiten', exact: true }).click();
  const editDialog = page.getByRole('dialog');
  await expect(editDialog).toHaveAccessibleName('Synthetische Qualitätsvorlage');
  await editDialog.getByRole('textbox', { name: 'Titel', exact: true }).fill('Geänderte Qualitätsvorlage');
  await expect(editDialog).toHaveAccessibleName('Geänderte Qualitätsvorlage');
  await editDialog.getByRole('textbox', { name: 'Text', exact: true }).fill('Überarbeitete Anhörung mit Umlauten.');
  await editDialog.getByRole('button', { name: 'Änderungen speichern', exact: true }).click();
  await expect(editDialog).not.toBeVisible();
  await expect(status).toHaveText('Vorlage wurde aktualisiert.');
  await expect(detail.getByRole('heading', { name: 'Geänderte Qualitätsvorlage', exact: true })).toBeVisible();
  await expect(detail).toContainText('Überarbeitete Anhörung mit Umlauten.');

  const deleteButton = region.getByRole('button', { name: 'Vorlage Geänderte Qualitätsvorlage löschen', exact: true });
  await deleteButton.click();
  const confirmation = page.getByRole('alertdialog', { name: 'Vorlage löschen?', exact: true });
  await expect(confirmation).toBeVisible();
  await confirmation.getByRole('button', { name: 'Abbrechen', exact: true }).click();
  await expect(confirmation).not.toBeVisible();
  await expect(deleteButton).toBeFocused();
  await expect(detail.getByRole('heading', { name: 'Geänderte Qualitätsvorlage', exact: true })).toBeVisible();
  await deleteButton.click();
  await confirmation.getByRole('button', { name: 'Vorlage löschen', exact: true }).focus();
  await page.keyboard.press('Enter');
  await expect(confirmation).not.toBeVisible();
  await expect(status).toHaveText('Vorlage wurde gelöscht.');
  await expect(deleteButton).toHaveCount(0);
  await expect(detail.getByRole('heading', { name: 'Geänderte Qualitätsvorlage', exact: true })).toHaveCount(0);
});
