import fs from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { describe, expect, it } from 'vitest';
import type { DatabaseAdapter } from '../../../services/databaseService';
import { SbvElectionService } from '../../../services/sbvElectionService';

class SqliteAdapter implements DatabaseAdapter {
  constructor(private readonly db: DatabaseSync) {}
  prepare<T=unknown>(sql:string){const statement=this.db.prepare(sql);return{all:(...params:unknown[])=>statement.all(...params as []) as T[],get:(...params:unknown[])=>statement.get(...params as []) as T|undefined,run:(...params:unknown[])=>statement.run(...params as [])};}
  exec(sql:string){this.db.exec(sql);} pragma(sql:string){return this.db.exec(`PRAGMA ${sql}`);} close(){this.db.close();}
}
function service(){const raw=new DatabaseSync(':memory:');raw.exec(fs.readFileSync('database/schema.sql','utf8'));return{raw,service:new SbvElectionService(new SqliteAdapter(raw))};}
const setup=(count:number,pending=0)=>({eligibilityCheckDate:'2026-08-16',confirmedSeverelyDisabledCount:count,confirmedEqualizedCount:0,pendingEqualizationCount:pending,spatiallySeparated:false,electionDate:'2026-11-12'} as const);

describe('SBV election preparation workflow 0.9.7-C',()=>{
 it('blocks 4 confirmed plus a pending equalization while allowing the fifth confirmed equalization',()=>{const {service:s}=service();const e=s.create({kind:'regular',electionDate:'2026-11-12'});expect(s.configureSetup(e.id,setup(4,1))).toMatchObject({eligibleCountSnapshot:4,minimumThresholdMet:false,startReady:false});const allowed=s.configureSetup(e.id,{...setup(4),confirmedEqualizedCount:1});expect(allowed).toMatchObject({eligibleCountSnapshot:5,minimumThresholdMet:true,startReady:true});expect(JSON.parse(s.get(e.id).eligibilityCheckBasis!)).toMatchObject({pendingEqualizationCount:0,confirmedEqualizedCount:1});});
 it('suggests simplified for 49 and formal for 50 but preserves an election-body override',()=>{const {service:s}=service();const a=s.create({kind:'extraordinary_no_sbv',triggerReason:'vakant',electionDate:'2026-09-20'});expect(s.configureSetup(a.id,{...setup(49),electionDate:'2026-09-20'}).suggestedProcedure).toBe('simplified');const b=s.create({kind:'extraordinary_no_sbv',triggerReason:'vakant',electionDate:'2026-09-20'});expect(s.configureSetup(b.id,{...setup(50),electionDate:'2026-09-20'}).suggestedProcedure).toBe('formal');expect(s.configureSetup(b.id,{...setup(50),electionDate:'2026-09-20',procedure:'simplified'})).toMatchObject({suggestedProcedure:'formal',selectedProcedure:'simplified',procedureDiffersFromSuggestion:true});});
 it('keeps the historical threshold snapshot unchanged when later voter entries change',()=>{const {service:s}=service();const e=s.create({kind:'extraordinary_no_sbv',triggerReason:'vakant'});s.configureSetup(e.id,{...setup(5),electionDate:undefined});s.saveVoter(e.id,{lastName:'Offen',firstName:'Antrag',eligibilityBasis:'pending_equalization_not_eligible'});s.saveVoter(e.id,{lastName:'Fest',firstName:'Gleich',eligibilityBasis:'equalized_confirmed'});expect(s.overview(e.id).voters.map(v=>v.listStatus)).toEqual(['eligible','not_eligible']);expect(s.get(e.id).eligibleCountSnapshot).toBe(5);});
 it('keeps formal and simplified deputy by-election paths explicit and inherits the remaining term',()=>{const {service:s}=service();const formal=s.create({kind:'deputy_by_election',triggerReason:'kein stellvertretendes Mitglied',incumbentTermEnd:'2028-04-26',electionDate:'2026-09-20'});s.configureSetup(formal.id,{...setup(50),electionDate:'2026-09-20'});expect(s.get(formal.id)).toMatchObject({procedure:'formal',officeTermEnd:'2028-04-26'});const simple=s.create({kind:'deputy_by_election',triggerReason:'kein stellvertretendes Mitglied',incumbentTermEnd:'2028-04-26',electionDate:'2026-09-20'});s.configureSetup(simple.id,{...setup(5),electionDate:'2026-09-20'});expect(s.get(simple.id)).toMatchObject({procedure:'simplified',officeTermEnd:'2028-04-26'});});
 it('creates formal deadlines centrally and journal prefill without persisting an entry',()=>{const {raw,service:s}=service();const e=s.create({kind:'regular',incumbentTermEnd:'2026-11-30',electionDate:'2026-11-12'});s.configureSetup(e.id,setup(50));s.saveBoardMember(e.id,{role:'chair',name:'A',adultConfirmed:true,employedConfirmed:true,appointedAt:'2026-09-01'});const deadlines=raw.prepare("SELECT source_event FROM deadlines WHERE process_type='election' AND process_id=? ORDER BY source_event").all(e.id) as Array<{source_event:string}>;expect(deadlines.map(x=>x.source_event)).toEqual(expect.arrayContaining(['formal.board.appoint','formal.candidates.publish','formal.election.target','formal.notice.publish']));expect(s.journalPrefill(e.id,'preparation').privacyNotice).toContain('noch kein Journaleintrag');expect((raw.prepare('SELECT COUNT(*) AS count FROM activity_journal_entries').get() as {count:number}).count).toBe(0);});
 it('enforces supporter count, locks deputies and applies the three-workday duplicate-candidature correction',()=>{const {raw,service:s}=service();const e=s.create({kind:'extraordinary_no_sbv',triggerReason:'vakant',electionDate:'2026-09-20'});s.configureSetup(e.id,{...setup(50),electionDate:'2026-09-20'});for(const name of ['A','B','C'])s.saveVoter(e.id,{lastName:name,firstName:'V',eligibilityBasis:'severely_disabled_confirmed'});const c=s.saveCandidate(e.id,{officeType:'representative',personSnapshot:'Kandidat',consentAt:'2026-08-18',ageOnElectionDay:30,monthsInOperation:12,operationAgeMonths:24,excludedFromRepresentativeBodyByLaw:false,notTemporaryEmployment:true});expect(()=>s.configureSetup(e.id,{...setup(50),electionDate:'2026-09-20',deputyCount:2})).toThrow(/fixiert/);const supporters=s.overview(e.id).voters.map(v=>v.id);expect(s.saveProposal(e.id,{receivedAt:'2026-08-18',validityStatus:'valid',candidateIds:[c.id],supporterVoterIds:supporters}).validityStatus).toBe('valid');const duplicate=s.saveProposal(e.id,{receivedAt:'2026-08-18',validityStatus:'valid',candidateIds:[c.id],supporterVoterIds:supporters});expect(duplicate).toMatchObject({validityStatus:'correction_required',correctionDueAt:'2026-08-21'});expect(raw.prepare("SELECT COUNT(*) AS count FROM deadlines WHERE source_event='formal.proposal.correction'").get()).toMatchObject({count:1});});

 it('requires correction when the same voter supports more than one formal proposal',()=>{const {raw,service:s}=service();const e=s.create({kind:'extraordinary_no_sbv',triggerReason:'vakant',electionDate:'2026-09-20'});s.configureSetup(e.id,{...setup(50),electionDate:'2026-09-20'});for(const name of ['A','B','C'])s.saveVoter(e.id,{lastName:name,firstName:'V',eligibilityBasis:'severely_disabled_confirmed'});const c1=s.saveCandidate(e.id,{officeType:'representative',personSnapshot:'Kandidat 1',consentAt:'2026-08-18',ageOnElectionDay:30,monthsInOperation:12,operationAgeMonths:24,excludedFromRepresentativeBodyByLaw:false,notTemporaryEmployment:true});const c2=s.saveCandidate(e.id,{officeType:'representative',personSnapshot:'Kandidat 2',consentAt:'2026-08-18',ageOnElectionDay:31,monthsInOperation:13,operationAgeMonths:24,excludedFromRepresentativeBodyByLaw:false,notTemporaryEmployment:true});const supporters=s.overview(e.id).voters.map(v=>v.id);expect(s.saveProposal(e.id,{receivedAt:'2026-08-18',validityStatus:'valid',candidateIds:[c1.id],supporterVoterIds:supporters}).validityStatus).toBe('valid');const second=s.saveProposal(e.id,{receivedAt:'2026-08-18',validityStatus:'valid',candidateIds:[c2.id],supporterVoterIds:supporters});expect(second).toMatchObject({validityStatus:'correction_required',invalidReason:'supporter_duplicate',correctionDueAt:'2026-08-21'});expect(raw.prepare("SELECT COUNT(*) AS count FROM deadlines WHERE source_event='formal.proposal.correction'").get()).toMatchObject({count:1});});
 it('reports a formal election-date conflict when the election exceeds the target after board appointment',()=>{const {service:s}=service();const e=s.create({kind:'extraordinary_office_end',triggerReason:'Amtsende',incumbentTermEnd:'2026-10-15',electionDate:'2026-10-20'});s.configureSetup(e.id,{...setup(50),electionDate:'2026-10-20'});s.saveBoardMember(e.id,{role:'chair',name:'A',adultConfirmed:true,employedConfirmed:true,appointedAt:'2026-09-01'});s.saveBoardMember(e.id,{role:'member',name:'B',adultConfirmed:true,employedConfirmed:true});s.saveBoardMember(e.id,{role:'member',name:'C',adultConfirmed:true,employedConfirmed:true});expect(s.overview(e.id).conflicts).toContain('Wahltermin überschreitet das Ziel für die unverzügliche Wahleinleitung.');expect(()=>s.markPreparation(e.id)).toThrow(/Wahltermin/);});
 it('starts objection and proposal deadlines only when the formal election notice is recorded as issued',()=>{const {raw,service:s}=service();const e=s.create({kind:'extraordinary_no_sbv',triggerReason:'vakant',electionDate:'2026-09-20'});s.configureSetup(e.id,{...setup(50),electionDate:'2026-09-20'});s.recordElectionNoticeIssued(e.id,'2026-08-18');const rows=raw.prepare("SELECT source_event,source_date,due_at FROM deadlines WHERE process_id=? AND source_event IN ('formal.voterlist.objection','formal.proposal.submit') ORDER BY source_event").all(e.id) as Array<{source_event:string;source_date:string;due_at:string}>;expect(rows).toHaveLength(2);expect(rows.every(r=>r.source_date==='2026-08-18'&&r.due_at.startsWith('2026-09-01'))).toBe(true);});
});
